services:
  db:
    image: postgres:16-alpine
    restart: always
    networks:
      - boards-network
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 4gaBoards
      POSTGRES_PASSWORD: notpassword
      POSTGRES_INITDB_ARGS: '-A scram-sha-256'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d 4gaBoards']
      interval: 1s
      timeout: 5s
      retries: 50

  4gaBoards:
    image: ghcr.io/rargames/4gaboards:latest
    restart: always
    networks:
      - boards-network
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      BASE_URL: http://localhost:3000
      SECRET_KEY: notsecretkey
      DATABASE_URL: postgresql://postgres:notpassword@db/4gaBoards
      NODE_ENV: production

      ## Optional

      ### Default settings (applied only on first run)

      #### Default admin user is always created, but you can override the default values:
      # DEFAULT_ADMIN_USERNAME: "demo" #Defaults to demo, this value overrides the default admin username
      # DEFAULT_ADMIN_EMAIL: "demo@demo.demo" #Defaults to demo@demo.dmeo, this value overrides the default admin email
      # DEFAULT_ADMIN_NAME: "Demo Demo" #Defaults to Demo Demo, this value overrides the default admin name
      # DEFAULT_ADMIN_PASSWORD: "demo" #Defaults to demo, this value overrides the default admin password

      #### Other settings:
      # DEFAULT_PROJECT_CREATION_ALL: true #Defaults to true, false = only admins can create projects
      # DEFAULT_REGISTRATION_ENABLED: true #Defaults to true, false = registration disabled
      # DEFAULT_LOCAL_REGISTRATION_ENABLED: true #Defaults to true, false = local registration disabled
      # DEFAULT_SSO_REGISTRATION_ENABLED: true #Defaults to true, false = SSO registration disabled

      ### Google OAuth2.0
      # GOOGLE_CLIENT_ID: googleClientId #Client id from the project on: https://console.cloud.google.com/
      # GOOGLE_CLIENT_SECRET: googleClientSecret #Secret from the project: generated in app settings

      ### GitHub OAuth2.0
      # GITHUB_CLIENT_ID: githubClientId #Client id from the app after creating on: https://github.com/settings/applications/new or https://github.com/settings/apps/new
      # GITHUB_CLIENT_SECRET: githubClientSecret #Client secret from the app: generated in app settings

      ### Microsoft OIDC
      # MICROSOFT_CLIENT_ID: microsoftClientId #Client id from the app after creating on: https://portal.azure.com/
      # MICROSOFT_CLIENT_SECRET: microsoftClientSecret #Client secret from the app: generated in app settings

      ### Other settings
      # DEMO_MODE: false #Defaults to false, true = demo mode enabled
      # LOG_LEVEL: warn #Log levels from highest to lowest - error, warn, info, http, verbose, debug, silly
      # TRUST_PROXY: 0
      # TOKEN_EXPIRES_IN: 365 #In days
      # CLIENT_URL=http://localhost:3000 #Main boards URL - usually not needed if running production defaults to BASE_URL, if development defaults to http://localhost:3000

    depends_on:
      db:
        condition: service_healthy

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
networks:
  boards-network:
