replicaCount: 1

image:
  repository: ghcr.io/rargames/4gaboards
  pullPolicy: Always
  tag: 'latest'

imagePullSecrets: []
nameOverride: 'app-4gaboards'
fullnameOverride: 'app-4gaboards'

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 1337

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
serviceAccount:
  create: false
postgresql:
  enabled: true
  auth:
    database: '4gaBoards'
    username: 'boards-user'
    password: 'notpassword'
    postgresPassword: 'adminPassword'
  postgresUrl: <URL> #Set only if using external postgres and postgresql.enabled: false
  volumePermissions:
    enabled: true
env:
  required:
    SECRET_KEY: notsecretkey
    BASE_URL: http://localhost:80
  optional:
    CLIENT_URL: http://localhost:80

    ### Default settings (applied only on first run)

    #### Default admin user is always created, but you can override the default values:
    # DEFAULT_ADMIN_USERNAME: "demo" #Defaults to demo, this value overrides the default admin username
    # DEFAULT_ADMIN_EMAIL: "demo@demo.demo" #Defaults to demo@demo.dmeo, this value overrides the default admin email
    # DEFAULT_ADMIN_NAME: "Demo Demo" #Defaults to Demo Demo, this value overrides the default admin name
    # DEFAULT_ADMIN_PASSWORD: "demo" #Defaults to demo, this value overrides the default admin password

    #### Other settings:
    # DEFAULT_PROJECT_CREATION_ALL: true #Defaults to true, false = only admins can create projects
    # DEFAULT_REGISTRATION_ENABLED: true #Defaults to true, false = registration disabled
    # DEFAULT_LOCAL_REGISTRATION_ENABLED: true #Defaults to true, false = local registration disabled
    # DEFAULT_SSO_REGISTRATION_ENABLED: true #Defaults to true, false = SSO registration disabled

    ### Google OAuth2.0
    # GOOGLE_CLIENT_ID: googleClientId #Client id from the project on: https://console.cloud.google.com/
    # GOOGLE_CLIENT_SECRET: googleClientSecret #Secret from the project: generated in app settings

    ### GitHub OAuth2.0
    # GITHUB_CLIENT_ID: githubClientId #Client id from the app after creating on: https://github.com/settings/applications/new or https://github.com/settings/apps/new
    # GITHUB_CLIENT_SECRET: githubClientSecret #Client secret from the app: generated in app settings

    ### Microsoft OIDC
    # MICROSOFT_CLIENT_ID: microsoftClientId #Client id from the app after creating on: https://portal.azure.com/
    # MICROSOFT_CLIENT_SECRET: microsoftClientSecret #Client secret from the app: generated in app settings

    ### Other settings
    # DEMO_MODE: false #Defaults to false, true = demo mode enabled
    # LOG_LEVEL: warn #Log levels from highest to lowest - error, warn, info, http, verbose, debug, silly
    # TRUST_PROXY: 0
    # TOKEN_EXPIRES_IN: 365 #In days

pv:
  storageClass: standard
  useravatars:
    pvcname: user-avatars
    size: 5Gi
  projectbackgroundimages:
    pvcname: project-background-images
    size: 5Gi
  attachments:
    pvcname: attachments
    size: 5Gi
